### PR TITLE
Mention discord rich presence and how to enable it

### PR DESCRIPTION
**Pull request by alixdotsh**
iirc there was nothing mentioning it

### CODE REVIEW

**Comment by dragongoose** [comment]
Mentioning it is great, though it would definitely be better if there was a prompt asking if you want it enabled or not.
It would also break with the precompiled releases because presence is broken on them.

**Comment by MasterIO02** [comment]
I think we don't need to mention the rich presence as a message in the client, but it should probably be in the readme with the other config options list.

**Comment by alixdotsh** [comment]
> I think we don't need to mention the rich presence as a message in the client, but it should probably be in the readme with the other config options list.

That's fair enough. It was just a quick thought I had.

**Comment by alixdotsh** [comment]
Added to the readme instead of the console. Idea comes based from @MasterIO02, but actual text is from @dragongoose as they didn’t want to open a new PR.

**Pull request merged**
